#!/bin/bash

bosh -e micro-bosh -d paasta-portal-api deploy paasta-portal-bosh2.0.yml \
   -o use-public-network-{IAAS}.yml \
   -v releases_name="paasta-portal-api-release"\
   -v stemcell_os="ubuntu-xenial"\
   -v stemcell_version="latest"\
   -v stemcell_alias="default"\
   -v vm_type_tiny="small"\
   -v vm_type_small="portal_small"\
   -v vm_type_medium="portal_medium"\
   -v internal_networks_name="default" \
   -v external_networks_name="vip" \
   -v mariadb_disk_type="10GB"\
   -v mariadb_port="3306"\
   -v mariadb_user_password="Paasta@2019"\
   -v binary_storage_disk_type="10GB"\
   -v binary_storage_username="paasta-portal"\
   -v binary_storage_password="paasta"\
   -v binary_storage_tenantname="paasta-portal"\
   -v binary_storage_email="paasta@paasta.com"\
   -v haproxy_public_ip="{xxx.xxx.xxx.xxx}"\
   -v cf_db_ips="10.174.0.53"\
   -v cf_db_port="5524"\
   -v cc_db_id="cloud_controller"\
   -v cc_db_password="{cf DB password}"\
   -v uaa_db_id="uaa"\
   -v uaa_db_password="{uaa DB password}"\
   -v cf_uaa_url="https://uaa.{xxx.xxx.xxx.xxx}.xip.io"\
   -v cf_uaa_logouturl="logout.do"\
   -v cf_api_url="https://api.{xxx.xxx.xxx.xxx}.xip.io"\
   -v cf_admin_password="admin"\
   -v cf_uaa_admin_client_secret="{uaa admin secret}"\
   -v paas_ta_web_user_url="http://portal-web-user.{xxx.xxx.xxx.xxx}.xip.io"\
   -v abacus_url="http://abacus.54.180.182.41.xip.io"\
   -v monitoring_api_url="http://monitoring.54.180.182.41.io"\
   -v mail_smtp_host="smtp.gmail.com"\
   -v mail_smtp_port="465"\
   -v mail_smtp_username="{smtp_user_name}"\
   -v mail_smtp_password="{smtp_password}"\
   -v mail_smtp_useremail="{smtp_email}"\
   -v mail_smtp_properties_auth="true"\
   -v mail_smtp_properties_starttls_enable="true"\
   -v mail_smtp_properties_starttls_required="true"\
   -v mail_smtp_properties_subject="PaaS-TA User Potal"\
   -v infra_admin=false
